# This file was generated by GoReleaser. DO NOT EDIT.
cask "sd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2fa8526475902c48e3b614348fa0f63392746a92dbe0272158f0e80b58354ebb"
      url "https://github.com/saddledata/sd-cli/releases/download/v#{version}/sd-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cc5fb92c87da58d1cd5c71545c501a38d3f4d7bf4b222413243a07d8aff85e47"
      url "https://github.com/saddledata/sd-cli/releases/download/v#{version}/sd-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a89af5d9a33448395d699083146974ebfd1c2a4ed20d4f6d695bb66605bbb10f"
      url "https://github.com/saddledata/sd-cli/releases/download/v#{version}/sd-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52793cc8a4fd2ac66d23685082e71ad1c9a1f5b790cefc9bd5b1f3aa1738512c"
      url "https://github.com/saddledata/sd-cli/releases/download/v#{version}/sd-cli_Linux_arm64.tar.gz"
    end
  end

  name "sd"
  desc "sd is the official command-line interface for Saddle Data."
  homepage "https://github.com/saddledata/sd-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sd"

  # No zap stanza required

end
