# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PiiHound < Formula
  desc "pii-hound sniffs out unprotected PII and secrets in your data sources."
  homepage "https://github.com/saddledata/pii-hound"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saddledata/pii-hound/releases/download/v0.1.6/pii-hound_Darwin_x86_64.tar.gz"
      sha256 "9bb9097ca5c7457c3312c94f35ce9c4de501501460960dd238a19108446863d9"

      define_method(:install) do
        bin.install "pii-hound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saddledata/pii-hound/releases/download/v0.1.6/pii-hound_Darwin_arm64.tar.gz"
      sha256 "a9531d4283f80593d43c3854701f0b5193be27e4696dad9d5f76212044209f46"

      define_method(:install) do
        bin.install "pii-hound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saddledata/pii-hound/releases/download/v0.1.6/pii-hound_Linux_x86_64.tar.gz"
      sha256 "acd4da784ba16e658a9ad962778f243d79d330086bbf929fa5ee783f742f805a"
      define_method(:install) do
        bin.install "pii-hound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saddledata/pii-hound/releases/download/v0.1.6/pii-hound_Linux_arm64.tar.gz"
      sha256 "8b90962c3db716bf3a85ca4d478ca41ef3876b2df20fcd4b0b579ba385d23bc1"
      define_method(:install) do
        bin.install "pii-hound"
      end
    end
  end

  test do
    system "#{bin}/pii-hound --version"
  end
end
