# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "sd is the official command-line interface for Saddle Data."
  homepage "https://github.com/saddledata/sd-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saddledata/sd-cli/releases/download/v0.0.1/sd-cli_Darwin_x86_64.tar.gz"
      sha256 "0466998d25b50637d2f193782ed2a8d249b64bae381ab0bfa0c061a468be56aa"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saddledata/sd-cli/releases/download/v0.0.1/sd-cli_Darwin_arm64.tar.gz"
      sha256 "1fd41ea976a9e977be6455f94705e5891f7023cadcdbcc97fe180ac416fa0c69"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saddledata/sd-cli/releases/download/v0.0.1/sd-cli_Linux_x86_64.tar.gz"
      sha256 "cdf4e8f22be147503c7306cfe25784dd67e75e12d1b489493980c05dc5830679"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saddledata/sd-cli/releases/download/v0.0.1/sd-cli_Linux_arm64.tar.gz"
      sha256 "848f5e2749cf4c1e56562aaee1ab4b05260ea9be87fe0e079b327998388ca83f"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    system "#{bin}/sd version"
  end
end
